const example_1 = {
    map:
    [[{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'start' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'end' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'dead' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'none' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }],
    [{ type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' },
    { type: 'block' }]],
        objects:
    [{
        type: 'movingPlatform',
        id: 'f1492fcb-6956-49e9-bd57-242d7132cf06',
        pos: { x: 904, y: 476 },
        name: 'movingPlatform',
        direction: 'left',
        distance: 19,
        speed: 'super fast'
    },
    {
        type: 'mucus',
        id: 'afa98ba1-090e-4244-a767-a13f24e7e84c',
        pos: { x: 904, y: 476 },
        name: 'mucus'
    },
    {
        type: 'bow',
        id: '3791f6cc-0b38-4ad1-9a33-31da7e3b59c0',
        pos: { x: 904, y: 476 },
        name: 'bow',
        direction: 'up',
        RoF: 'fast'
    },
    {
        type: 'platform',
        id: 'd41c0b8f-f320-4ec7-a86a-49d3543dc5c8',
        pos: { x: 392, y: 284 },
        name: 'platform'
    },
    {
        type: 'movingPlatform',
        id: '8b6a9e8b-7f31-450f-aa96-b928800d9768',
        pos: { x: 456, y: 316 },
        name: 'movingPlatform',
        direction: 'down',
        distance: 2,
        speed: 'normal'
    },
    {
        type: 'spikedBlock',
        id: 'da8c566e-58bd-4b96-99bc-265a095b4234',
        pos: { x: 456, y: 316 },
        name: 'spikedBlock',
        upSpike: true,
        downSpike: false,
        leftSpike: false,
        rightSpike: false
    },
    {
        type: 'mucus',
        id: '45cd0c06-92f0-46af-a775-5c8a5dd7c8f7',
        pos: { x: 456, y: 316 },
        name: 'mucus'
    },
    {
        type: 'platform',
        id: '0273de6b-f845-4d03-941c-61ed16445640',
        pos: { x: 296, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '8cc4d5a6-18f8-440f-8fc5-58c630274b1d',
        pos: { x: 328, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '66de3ecf-098d-424a-a6a6-68f298cecf6a',
        pos: { x: 360, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'cc981405-8065-495b-9e9d-d31ce5845608',
        pos: { x: 424, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '026386b7-d26b-46e8-a260-70fffe357361',
        pos: { x: 456, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '3aca7009-eaee-44ee-93f6-42e54a7aae99',
        pos: { x: 488, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '4ff1a7ee-7f00-4305-abc7-279a184f865a',
        pos: { x: 520, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '9101afa5-4487-4925-be80-5e19046d339d',
        pos: { x: 552, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '6002e55e-d73a-4e72-81c4-4ca7e45be5a4',
        pos: { x: 584, y: 284 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '632cc951-c4a4-454d-afdb-55ee015f5655',
        pos: { x: 616, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'bc5cca8a-815f-4282-b714-b8252bef1587',
        pos: { x: 648, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'dc21f1c9-969f-461c-882d-988dec347bd8',
        pos: { x: 680, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'ffa4c421-8c41-4351-b8de-329fd361cc7b',
        pos: { x: 712, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '0f62982e-7509-4bd8-b2fe-3c879ea65212',
        pos: { x: 744, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'fbdc2b60-2990-4d88-bef3-a14efd3c2b0e',
        pos: { x: 776, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'de893e47-78b7-4c69-ad13-c06f29c559ad',
        pos: { x: 808, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '563017f7-fe8d-4363-bb60-5210d71a2eee',
        pos: { x: 840, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'dc87ca03-9518-4003-9266-4efc41e748da',
        pos: { x: 872, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '15b1b3f0-56d7-4d4b-af00-28b7d7f6bbdc',
        pos: { x: 904, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: '2416159e-8578-4aaf-80e4-e611c953fdda',
        pos: { x: 584, y: 316 },
        name: 'platform'
    },
    {
        type: 'platform',
        id: 'b0048271-74d0-4bb2-a61a-5ca7b4a7954f',
        pos: { x: 616, y: 284 },
        name: 'platform'
    },
    {
        type: 'movingPlatform',
        id: 'b97bb1bc-6c80-430e-b421-8aaadb3b3485',
        pos: { x: 776, y: 284 },
        name: 'movingPlatform',
        direction: 'up',
        distance: 2,
        speed: 'normal'
    },
    {
        type: 'mucus',
        id: 'e71fe0d3-86f1-4e15-9cb8-d8342fe318df',
        pos: { x: 776, y: 284 },
        name: 'mucus'
    },
    {
        type: 'spikedBlock',
        id: 'a45c5b20-a987-4c9d-87b3-2d2c89b93ccd',
        pos: { x: 776, y: 284 },
        name: 'spikedBlock',
        upSpike: false,
        downSpike: true,
        leftSpike: false,
        rightSpike: false
    },
    {
        type: 'movingPlatform',
        id: 'f6aa6c74-9efb-4788-b3a9-c1e053644f21',
        pos: { x: 296, y: 124 },
        name: 'movingPlatform',
        direction: 'right',
        distance: 19,
        speed: 'super fast'
    },
    {
        type: 'mucus',
        id: 'a5acb2a1-1972-4764-aad2-abf420f749ce',
        pos: { x: 296, y: 124 },
        name: 'mucus'
    },
    {
        type: 'bow',
        id: '7fe7b219-0afb-4fa1-93f4-91ccba3658c6',
        pos: { x: 296, y: 124 },
        name: 'bow',
        direction: 'down',
        RoF: 'fast'
    }]
}

export default example_1;